remote_theme: mmistakes/minimal-mistakes@4.24.0 #pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: Gianmarco Aversano
subtitle: Ph.D., Data Scientist and A.I. Engineer.
name: Gianmarco Aversano
description: Professional website
logo: pics/me.jpg
layout: single
github:
  owner_url: https://github.com/svnv-svsv-jm

# Site Author
author:
  name: "Gianmarco Aversano"
  avatar: pics/me.jpg
  bio: "Ph.D., Data Scientist and A.I. Engineer."
  location: "Berlin, Germany."
  email: Gianmarco.Aversano1990@gmail.com
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:Gianmarco.Aversano1990@gmail.com"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/gianmarco-aversano/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/svnv-svsv-jm"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:Gianmarco.Aversano1990@gmail.com"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/gianmarco-aversano/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/svnv-svsv-jm"