remote_theme: mmistakes/minimal-mistakes@4.24.0 #pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: Gianmarco Aversano

description: Professional website

github:
  owner_url: https://github.com/svnv-svsv-jm
