title: Gianmarco Aversano
subtitle: Ph.D., Data Scientist and A.I. Engineer.
email: Gianmarco.Aversano1990@gmail.com
description: Personal website and blog of Gianmarco Aversano.

minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Gianmarco Aversano"
  avatar: "/assets/images/me.jpg"
  bio: "Ph.D., Data Scientist and A.I. Engineer."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:Gianmarco.Aversano1990@gmail.com"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/gianmarco-aversano/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/svnv-svsv-jm"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:Gianmarco.Aversano1990@gmail.com"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/gianmarco-aversano/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/svnv-svsv-jm"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
